#define inti_dt 1
#define bool_dt 2
#define string_dt 3
#define giveInti 4
#define sayInti 5
#define say 6
#define give 7
#define adiosBoys 8
#define hmm 9
#define nah 10
#define and 11
#define or 12
#define repeatAfterMe 13
#define id 14
#define ct 15
#define plus 16
#define MINUS 17
#define MULTIPLY 18
#define DIVISION 19
#define REMAINDER 20
#define LESS 21
#define LESS_OR_EQUAL 22
#define EQUAL 23
#define GREATER_OR_EQUAL 24
#define GREATER 25
#define ASSIGN 26
#define OPEN_ACCOL 27
#define CLOSED_ACCOL 28
#define OPEN_SQUARE 29
#define CLOSED_SQUARE 30
#define OPEN_ROUND 31
#define CLOSED_ROUND 32
#define SEMI_COL 33
#define COMMA 34